# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'canlisen.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_sensorliveform(object):
    def setupUi(self, sensorliveform):
        sensorliveform.setObjectName("sensorliveform")
        sensorliveform.resize(1057, 776)
        sensorliveform.setStyleSheet("background-color: rgb(105, 105, 105);\n"
"\n"
"\n"
"")
        self.widgetsensorlive = MatplotlibbWidget(sensorliveform)
        self.widgetsensorlive.setGeometry(QtCore.QRect(10, 10, 1041, 681))
        self.widgetsensorlive.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.widgetsensorlive.setObjectName("widgetsensorlive")
        self.livesensorbackbutton = QtWidgets.QPushButton(sensorliveform)
        self.livesensorbackbutton.setGeometry(QtCore.QRect(580, 700, 241, 61))
        font = QtGui.QFont()
        font.setFamily("Segoe Print")
        font.setPointSize(8)
        self.livesensorbackbutton.setFont(font)
        self.livesensorbackbutton.setStyleSheet("background:rgb(150, 27, 70);\n"
"border:none;\n"
"border-radius:30px;\n"
"color:white;")
        self.livesensorbackbutton.setObjectName("livesensorbackbutton")
        self.socketbaglantibutton = QtWidgets.QPushButton(sensorliveform)
        self.socketbaglantibutton.setGeometry(QtCore.QRect(260, 700, 241, 61))
        font = QtGui.QFont()
        font.setFamily("Segoe Print")
        font.setPointSize(8)
        self.socketbaglantibutton.setFont(font)
        self.socketbaglantibutton.setStyleSheet("background:rgb(150, 27, 70);\n"
"border:none;\n"
"border-radius:30px;\n"
"color:white;")
        self.socketbaglantibutton.setObjectName("socketbaglantibutton")

        self.retranslateUi(sensorliveform)
        QtCore.QMetaObject.connectSlotsByName(sensorliveform)

    def retranslateUi(self, sensorliveform):
        _translate = QtCore.QCoreApplication.translate
        sensorliveform.setWindowTitle(_translate("sensorliveform", "Form"))
        self.livesensorbackbutton.setText(_translate("sensorliveform", "BACK"))
        self.socketbaglantibutton.setText(_translate("sensorliveform", "Connect to Pi"))
from sensormatplotlibwidget import MatplotlibbWidget


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    sensorliveform = QtWidgets.QWidget()
    ui = Ui_sensorliveform()
    ui.setupUi(sensorliveform)
    sensorliveform.show()
    sys.exit(app.exec_())
