# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'degiskenlerbutons.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_degiskenler(object):
    def setupUi(self, degiskenler):
        degiskenler.setObjectName("degiskenler")
        degiskenler.resize(1111, 795)
        degiskenler.setStyleSheet("")
        self.widget = QtWidgets.QWidget(degiskenler)
        self.widget.setEnabled(True)
        self.widget.setGeometry(QtCore.QRect(30, 30, 1051, 691))
        self.widget.setStyleSheet("background-color: rgb(105,105,105);")
        self.widget.setObjectName("widget")
        self.picture = QtWidgets.QLabel(self.widget)
        self.picture.setGeometry(QtCore.QRect(0, 0, 561, 691))
        self.picture.setStyleSheet("border-image: url(:/images/zyro-image.png);\n"
"")
        self.picture.setText("")
        self.picture.setObjectName("picture")
        self.bilgiyazi = QtWidgets.QLabel(self.widget)
        self.bilgiyazi.setGeometry(QtCore.QRect(580, 40, 421, 121))
        font = QtGui.QFont()
        font.setFamily("Segoe Print")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.bilgiyazi.setFont(font)
        self.bilgiyazi.setStyleSheet("color: rgb(255, 255, 255);")
        self.bilgiyazi.setObjectName("bilgiyazi")
        self.temperaturebutton = QtWidgets.QPushButton(self.widget)
        self.temperaturebutton.setGeometry(QtCore.QRect(650, 520, 291, 71))
        font = QtGui.QFont()
        font.setFamily("Segoe Print")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.temperaturebutton.setFont(font)
        self.temperaturebutton.setStyleSheet("background:rgb(150, 27, 70);\n"
"border:none;\n"
"border-radius:30px;\n"
"color:white;")
        self.temperaturebutton.setObjectName("temperaturebutton")
        self.humiditybutton = QtWidgets.QPushButton(self.widget)
        self.humiditybutton.setGeometry(QtCore.QRect(650, 430, 291, 71))
        font = QtGui.QFont()
        font.setFamily("Segoe Print")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.humiditybutton.setFont(font)
        self.humiditybutton.setStyleSheet("background:rgb(150, 27, 70);\n"
"border:none;\n"
"border-radius:30px;\n"
"color:white;")
        self.humiditybutton.setObjectName("humiditybutton")
        self.gasbutton = QtWidgets.QPushButton(self.widget)
        self.gasbutton.setGeometry(QtCore.QRect(650, 340, 281, 71))
        font = QtGui.QFont()
        font.setFamily("Segoe Print")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.gasbutton.setFont(font)
        self.gasbutton.setStyleSheet("background:rgb(150, 27, 70);\n"
"border:none;\n"
"border-radius:30px;\n"
"color:white;")
        self.gasbutton.setObjectName("gasbutton")
        self.pressurebutton = QtWidgets.QPushButton(self.widget)
        self.pressurebutton.setGeometry(QtCore.QRect(650, 250, 281, 71))
        font = QtGui.QFont()
        font.setFamily("Segoe Print")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pressurebutton.setFont(font)
        self.pressurebutton.setStyleSheet("background:rgb(150, 27, 70);\n"
"border:none;\n"
"border-radius:30px;\n"
"color:white;")
        self.pressurebutton.setObjectName("pressurebutton")
        self.live_sensor_button = QtWidgets.QPushButton(self.widget)
        self.live_sensor_button.setGeometry(QtCore.QRect(650, 160, 281, 71))
        font = QtGui.QFont()
        font.setFamily("Segoe Print")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.live_sensor_button.setFont(font)
        self.live_sensor_button.setStyleSheet("background:rgb(150, 27, 70);\n"
"border:none;\n"
"border-radius:30px;\n"
"color:white;")
        self.live_sensor_button.setObjectName("live_sensor_button")

        self.retranslateUi(degiskenler)
        QtCore.QMetaObject.connectSlotsByName(degiskenler)

    def retranslateUi(self, degiskenler):
        _translate = QtCore.QCoreApplication.translate
        degiskenler.setWindowTitle(_translate("degiskenler", "Form"))
        self.bilgiyazi.setText(_translate("degiskenler", "Select the graphic you want to see"))
        self.temperaturebutton.setText(_translate("degiskenler", "Temperature Forecast Graph"))
        self.humiditybutton.setText(_translate("degiskenler", "Humidity Forecast Graph"))
        self.gasbutton.setText(_translate("degiskenler", "Gas Forecast Graph"))
        self.pressurebutton.setText(_translate("degiskenler", "Pressure Forecast Graph"))
        self.live_sensor_button.setText(_translate("degiskenler", "Live Sensor Data"))
import res_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    degiskenler = QtWidgets.QWidget()
    ui = Ui_degiskenler()
    ui.setupUi(degiskenler)
    degiskenler.show()
    sys.exit(app.exec_())
