# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gaspre.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_gaspreform(object):
    def setupUi(self, gaspreform):
        gaspreform.setObjectName("gaspreform")
        gaspreform.resize(1057, 776)
        gaspreform.setStyleSheet("background-color: rgb(105, 105, 105);\n"
"\n"
"\n"
"")
        self.widgetgaspre = MatplotlibWidget(gaspreform)
        self.widgetgaspre.setGeometry(QtCore.QRect(50, 70, 941, 541))
        self.widgetgaspre.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.widgetgaspre.setObjectName("widgetgaspre")
        self.gasprebackbutton = QtWidgets.QPushButton(gaspreform)
        self.gasprebackbutton.setGeometry(QtCore.QRect(560, 650, 241, 61))
        font = QtGui.QFont()
        font.setFamily("Segoe Print")
        font.setPointSize(8)
        self.gasprebackbutton.setFont(font)
        self.gasprebackbutton.setStyleSheet("background:rgb(150, 27, 70);\n"
"border:none;\n"
"border-radius:30px;\n"
"color:white;")
        self.gasprebackbutton.setObjectName("gasprebackbutton")
        self.gaspreforecastbutton = QtWidgets.QPushButton(gaspreform)
        self.gaspreforecastbutton.setGeometry(QtCore.QRect(260, 650, 241, 61))
        font = QtGui.QFont()
        font.setFamily("Segoe Print")
        font.setPointSize(8)
        self.gaspreforecastbutton.setFont(font)
        self.gaspreforecastbutton.setStyleSheet("background:rgb(150, 27, 70);\n"
"border:none;\n"
"border-radius:30px;\n"
"color:white;")
        self.gaspreforecastbutton.setObjectName("gaspreforecastbutton")

        self.retranslateUi(gaspreform)
        QtCore.QMetaObject.connectSlotsByName(gaspreform)

    def retranslateUi(self, gaspreform):
        _translate = QtCore.QCoreApplication.translate
        gaspreform.setWindowTitle(_translate("gaspreform", "Form"))
        self.gasprebackbutton.setText(_translate("gaspreform", "BACK"))
        self.gaspreforecastbutton.setText(_translate("gaspreform", "See Forecast Chart"))
from mmatplotlibwidget import MatplotlibWidget


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    gaspreform = QtWidgets.QWidget()
    ui = Ui_gaspreform()
    ui.setupUi(gaspreform)
    gaspreform.show()
    sys.exit(app.exec_())
