# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'girisekran.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_anaekranform(object):
    def setupUi(self, anaekranform):
        anaekranform.setObjectName("anaekranform")
        anaekranform.resize(1111, 795)
        anaekranform.setStyleSheet("")
        self.widget = QtWidgets.QWidget(anaekranform)
        self.widget.setEnabled(True)
        self.widget.setGeometry(QtCore.QRect(60, 30, 1001, 691))
        self.widget.setStyleSheet("background-color: rgb(105,105,105);\n"
"")
        self.widget.setObjectName("widget")
        self.picture = QtWidgets.QLabel(self.widget)
        self.picture.setGeometry(QtCore.QRect(0, 0, 541, 691))
        self.picture.setStyleSheet("border-image: url(:/images/zyro-image.png);\n"
"")
        self.picture.setText("")
        self.picture.setObjectName("picture")
        self.lgnyazi = QtWidgets.QLabel(self.widget)
        self.lgnyazi.setGeometry(QtCore.QRect(640, 50, 221, 111))
        font = QtGui.QFont()
        font.setFamily("Segoe Print")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.lgnyazi.setFont(font)
        self.lgnyazi.setStyleSheet("color: rgb(255, 255, 255);")
        self.lgnyazi.setObjectName("lgnyazi")
        self.usernamelineEdit = QtWidgets.QLineEdit(self.widget)
        self.usernamelineEdit.setGeometry(QtCore.QRect(610, 180, 321, 81))
        font = QtGui.QFont()
        font.setFamily("Segoe Print")
        font.setPointSize(16)
        self.usernamelineEdit.setFont(font)
        self.usernamelineEdit.setStyleSheet("background:rgb(70, 15, 87);\n"
"background-color: rgb(27, 51, 136);\n"
"border:none;\n"
"border-radius:30px;\n"
"color:white;\n"
"")
        self.usernamelineEdit.setText("")
        self.usernamelineEdit.setObjectName("usernamelineEdit")
        self.passwordlineEdit = QtWidgets.QLineEdit(self.widget)
        self.passwordlineEdit.setGeometry(QtCore.QRect(610, 290, 321, 81))
        font = QtGui.QFont()
        font.setFamily("Segoe Print")
        font.setPointSize(16)
        self.passwordlineEdit.setFont(font)
        self.passwordlineEdit.setStyleSheet("background:rgb(70, 15, 87);\n"
"background-color: rgb(27, 51, 136);\n"
"border:none;\n"
"border-radius:30px;\n"
"color:white;\n"
"")
        self.passwordlineEdit.setText("")
        self.passwordlineEdit.setObjectName("passwordlineEdit")
        self.loginbutton = QtWidgets.QPushButton(self.widget)
        self.loginbutton.setGeometry(QtCore.QRect(650, 410, 241, 71))
        font = QtGui.QFont()
        font.setFamily("Segoe Print")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.loginbutton.setFont(font)
        self.loginbutton.setStyleSheet("background:rgb(150, 27, 70);\n"
"border:none;\n"
"border-radius:30px;\n"
"color:white;")
        self.loginbutton.setObjectName("loginbutton")
        self.siginbutton = QtWidgets.QPushButton(self.widget)
        self.siginbutton.setGeometry(QtCore.QRect(650, 500, 241, 71))
        font = QtGui.QFont()
        font.setFamily("Segoe Print")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.siginbutton.setFont(font)
        self.siginbutton.setStyleSheet("background:rgb(150, 27, 70);\n"
"border:none;\n"
"border-radius:30px;\n"
"color:white;")
        self.siginbutton.setObjectName("siginbutton")

        self.retranslateUi(anaekranform)
        QtCore.QMetaObject.connectSlotsByName(anaekranform)

    def retranslateUi(self, anaekranform):
        _translate = QtCore.QCoreApplication.translate
        anaekranform.setWindowTitle(_translate("anaekranform", "Form"))
        self.lgnyazi.setText(_translate("anaekranform", "      LOG IN"))
        self.usernamelineEdit.setToolTip(_translate("anaekranform", "<html><head/><body><p>sgsgsg<br/></p></body></html>"))
        self.usernamelineEdit.setPlaceholderText(_translate("anaekranform", "        Username"))
        self.passwordlineEdit.setPlaceholderText(_translate("anaekranform", "        Password"))
        self.loginbutton.setText(_translate("anaekranform", "Log in"))
        self.siginbutton.setText(_translate("anaekranform", "Sig in"))
import res_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    anaekranform = QtWidgets.QWidget()
    ui = Ui_anaekranform()
    ui.setupUi(anaekranform)
    anaekranform.show()
    sys.exit(app.exec_())
