# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'hesapolustur.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_kayitekranfrom(object):
    def setupUi(self, kayitekranfrom):
        kayitekranfrom.setObjectName("kayitekranfrom")
        kayitekranfrom.resize(1111, 795)
        kayitekranfrom.setStyleSheet("")
        self.widget = QtWidgets.QWidget(kayitekranfrom)
        self.widget.setEnabled(True)
        self.widget.setGeometry(QtCore.QRect(80, 50, 1001, 691))
        self.widget.setStyleSheet("background-color: rgb(105,105,105);")
        self.widget.setObjectName("widget")
        self.picturei = QtWidgets.QLabel(self.widget)
        self.picturei.setGeometry(QtCore.QRect(0, 0, 541, 691))
        self.picturei.setStyleSheet("border-image: url(:/images/zyro-image.png);\n"
"\n"
"")
        self.picturei.setText("")
        self.picturei.setObjectName("picturei")
        self.sgnyazi = QtWidgets.QLabel(self.widget)
        self.sgnyazi.setGeometry(QtCore.QRect(640, 10, 221, 111))
        font = QtGui.QFont()
        font.setFamily("Segoe Print")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.sgnyazi.setFont(font)
        self.sgnyazi.setStyleSheet("color: rgb(255, 255, 255);")
        self.sgnyazi.setObjectName("sgnyazi")
        self.usernamelineEdit_2 = QtWidgets.QLineEdit(self.widget)
        self.usernamelineEdit_2.setGeometry(QtCore.QRect(610, 130, 321, 81))
        font = QtGui.QFont()
        font.setFamily("Segoe Print")
        font.setPointSize(16)
        self.usernamelineEdit_2.setFont(font)
        self.usernamelineEdit_2.setStyleSheet("background:rgb(70, 15, 87);\n"
"background-color: rgb(27, 51, 136);\n"
"border:none;\n"
"border-radius:30px;\n"
"color:white;\n"
"")
        self.usernamelineEdit_2.setText("")
        self.usernamelineEdit_2.setObjectName("usernamelineEdit_2")
        self.passwordlineEdit_2 = QtWidgets.QLineEdit(self.widget)
        self.passwordlineEdit_2.setGeometry(QtCore.QRect(610, 230, 321, 81))
        font = QtGui.QFont()
        font.setFamily("Segoe Print")
        font.setPointSize(16)
        self.passwordlineEdit_2.setFont(font)
        self.passwordlineEdit_2.setStyleSheet("background:rgb(70, 15, 87);\n"
"background-color: rgb(27, 51, 136);\n"
"border:none;\n"
"border-radius:30px;\n"
"color:white;\n"
"")
        self.passwordlineEdit_2.setText("")
        self.passwordlineEdit_2.setObjectName("passwordlineEdit_2")
        self.adduserbutton = QtWidgets.QPushButton(self.widget)
        self.adduserbutton.setGeometry(QtCore.QRect(650, 450, 241, 71))
        font = QtGui.QFont()
        font.setFamily("Segoe Print")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.adduserbutton.setFont(font)
        self.adduserbutton.setStyleSheet("background:rgb(150, 27, 70);\n"
"border:none;\n"
"border-radius:30px;\n"
"color:white;")
        self.adduserbutton.setObjectName("adduserbutton")
        self.loginbutton_2 = QtWidgets.QPushButton(self.widget)
        self.loginbutton_2.setGeometry(QtCore.QRect(650, 550, 241, 71))
        font = QtGui.QFont()
        font.setFamily("Segoe Print")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.loginbutton_2.setFont(font)
        self.loginbutton_2.setStyleSheet("background:rgb(150, 27, 70);\n"
"border:none;\n"
"border-radius:30px;\n"
"color:white;")
        self.loginbutton_2.setObjectName("loginbutton_2")
        self.gmailLineEdit_3 = QtWidgets.QLineEdit(self.widget)
        self.gmailLineEdit_3.setGeometry(QtCore.QRect(610, 330, 321, 81))
        font = QtGui.QFont()
        font.setFamily("Segoe Print")
        font.setPointSize(16)
        self.gmailLineEdit_3.setFont(font)
        self.gmailLineEdit_3.setStyleSheet("background:rgb(70, 15, 87);\n"
"background-color: rgb(27, 51, 136);\n"
"border:none;\n"
"border-radius:30px;\n"
"color:white;\n"
"")
        self.gmailLineEdit_3.setText("")
        self.gmailLineEdit_3.setObjectName("gmailLineEdit_3")

        self.retranslateUi(kayitekranfrom)
        QtCore.QMetaObject.connectSlotsByName(kayitekranfrom)

    def retranslateUi(self, kayitekranfrom):
        _translate = QtCore.QCoreApplication.translate
        kayitekranfrom.setWindowTitle(_translate("kayitekranfrom", "Form"))
        self.sgnyazi.setText(_translate("kayitekranfrom", "      SIG IN"))
        self.usernamelineEdit_2.setToolTip(_translate("kayitekranfrom", "<html><head/><body><p>sgsgsg<br/></p></body></html>"))
        self.usernamelineEdit_2.setPlaceholderText(_translate("kayitekranfrom", "        Username"))
        self.passwordlineEdit_2.setPlaceholderText(_translate("kayitekranfrom", "        Password"))
        self.adduserbutton.setText(_translate("kayitekranfrom", "Add User"))
        self.loginbutton_2.setText(_translate("kayitekranfrom", "Log in"))
        self.gmailLineEdit_3.setPlaceholderText(_translate("kayitekranfrom", "  example@gmail.com"))
import res_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    kayitekranfrom = QtWidgets.QWidget()
    ui = Ui_kayitekranfrom()
    ui.setupUi(kayitekranfrom)
    kayitekranfrom.show()
    sys.exit(app.exec_())
