# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'humiditypre.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_humidityform(object):
    def setupUi(self, humidityform):
        humidityform.setObjectName("humidityform")
        humidityform.resize(1057, 776)
        humidityform.setStyleSheet("background-color: rgb(105, 105, 105);\n"
"\n"
"\n"
"")
        self.widgethumidtypre = MatplotlibWidget(humidityform)
        self.widgethumidtypre.setGeometry(QtCore.QRect(50, 70, 941, 541))
        self.widgethumidtypre.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.widgethumidtypre.setObjectName("widgethumidtypre")
        self.humidityprebackbutton = QtWidgets.QPushButton(humidityform)
        self.humidityprebackbutton.setGeometry(QtCore.QRect(560, 650, 241, 61))
        font = QtGui.QFont()
        font.setFamily("Segoe Print")
        font.setPointSize(8)
        self.humidityprebackbutton.setFont(font)
        self.humidityprebackbutton.setStyleSheet("background:rgb(150, 27, 70);\n"
"border:none;\n"
"border-radius:30px;\n"
"color:white;")
        self.humidityprebackbutton.setObjectName("humidityprebackbutton")
        self.humiditypreforecastbutton = QtWidgets.QPushButton(humidityform)
        self.humiditypreforecastbutton.setGeometry(QtCore.QRect(260, 650, 241, 61))
        font = QtGui.QFont()
        font.setFamily("Segoe Print")
        font.setPointSize(8)
        self.humiditypreforecastbutton.setFont(font)
        self.humiditypreforecastbutton.setStyleSheet("background:rgb(150, 27, 70);\n"
"border:none;\n"
"border-radius:30px;\n"
"color:white;")
        self.humiditypreforecastbutton.setObjectName("humiditypreforecastbutton")

        self.retranslateUi(humidityform)
        QtCore.QMetaObject.connectSlotsByName(humidityform)

    def retranslateUi(self, humidityform):
        _translate = QtCore.QCoreApplication.translate
        humidityform.setWindowTitle(_translate("humidityform", "Form"))
        self.humidityprebackbutton.setText(_translate("humidityform", "BACK"))
        self.humiditypreforecastbutton.setText(_translate("humidityform", "See Forecast Chart"))
from mmatplotlibwidget import MatplotlibWidget


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    humidityform = QtWidgets.QWidget()
    ui = Ui_humidityform()
    ui.setupUi(humidityform)
    humidityform.show()
    sys.exit(app.exec_())
