# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'pressurepre.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_pressurepreform(object):
    def setupUi(self, pressurepreform):
        pressurepreform.setObjectName("pressurepreform")
        pressurepreform.resize(1057, 776)
        pressurepreform.setStyleSheet("background-color: rgb(105, 105, 105);\n"
"\n"
"\n"
"")
        self.widgetpressurepre = MatplotlibWidget(pressurepreform)
        self.widgetpressurepre.setGeometry(QtCore.QRect(50, 70, 941, 541))
        self.widgetpressurepre.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.widgetpressurepre.setObjectName("widgetpressurepre")
        self.pressureprebackbutton = QtWidgets.QPushButton(pressurepreform)
        self.pressureprebackbutton.setGeometry(QtCore.QRect(560, 650, 241, 61))
        font = QtGui.QFont()
        font.setFamily("Segoe Print")
        font.setPointSize(8)
        self.pressureprebackbutton.setFont(font)
        self.pressureprebackbutton.setStyleSheet("background:rgb(150, 27, 70);\n"
"border:none;\n"
"border-radius:30px;\n"
"color:white;")
        self.pressureprebackbutton.setObjectName("pressureprebackbutton")
        self.pressurepreforecastbutton = QtWidgets.QPushButton(pressurepreform)
        self.pressurepreforecastbutton.setGeometry(QtCore.QRect(260, 650, 241, 61))
        font = QtGui.QFont()
        font.setFamily("Segoe Print")
        font.setPointSize(8)
        self.pressurepreforecastbutton.setFont(font)
        self.pressurepreforecastbutton.setStyleSheet("background:rgb(150, 27, 70);\n"
"border:none;\n"
"border-radius:30px;\n"
"color:white;")
        self.pressurepreforecastbutton.setObjectName("pressurepreforecastbutton")

        self.retranslateUi(pressurepreform)
        QtCore.QMetaObject.connectSlotsByName(pressurepreform)

    def retranslateUi(self, pressurepreform):
        _translate = QtCore.QCoreApplication.translate
        pressurepreform.setWindowTitle(_translate("pressurepreform", "Form"))
        self.pressureprebackbutton.setText(_translate("pressurepreform", "BACK"))
        self.pressurepreforecastbutton.setText(_translate("pressurepreform", "See Forecast Chart"))
from mmatplotlibwidget import MatplotlibWidget


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    pressurepreform = QtWidgets.QWidget()
    ui = Ui_pressurepreform()
    ui.setupUi(pressurepreform)
    pressurepreform.show()
    sys.exit(app.exec_())
