# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'temperaturepre.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_temperaturepreform(object):
    def setupUi(self, temperaturepreform):
        temperaturepreform.setObjectName("temperaturepreform")
        temperaturepreform.resize(1057, 776)
        temperaturepreform.setStyleSheet("background-color: rgb(105, 105, 105);\n"
"\n"
"\n"
"")
        self.widgettemperaturepre = MatplotlibWidget(temperaturepreform)
        self.widgettemperaturepre.setGeometry(QtCore.QRect(50, 70, 941, 541))
        self.widgettemperaturepre.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.widgettemperaturepre.setObjectName("widgettemperaturepre")
        self.temperatureprebackbutton = QtWidgets.QPushButton(temperaturepreform)
        self.temperatureprebackbutton.setGeometry(QtCore.QRect(560, 650, 241, 61))
        font = QtGui.QFont()
        font.setFamily("Segoe Print")
        font.setPointSize(8)
        self.temperatureprebackbutton.setFont(font)
        self.temperatureprebackbutton.setStyleSheet("background:rgb(150, 27, 70);\n"
"border:none;\n"
"border-radius:30px;\n"
"color:white;")
        self.temperatureprebackbutton.setObjectName("temperatureprebackbutton")
        self.temperaturepreforecastbutton = QtWidgets.QPushButton(temperaturepreform)
        self.temperaturepreforecastbutton.setGeometry(QtCore.QRect(260, 650, 241, 61))
        font = QtGui.QFont()
        font.setFamily("Segoe Print")
        font.setPointSize(8)
        self.temperaturepreforecastbutton.setFont(font)
        self.temperaturepreforecastbutton.setStyleSheet("background:rgb(150, 27, 70);\n"
"border:none;\n"
"border-radius:30px;\n"
"color:white;")
        self.temperaturepreforecastbutton.setObjectName("temperaturepreforecastbutton")

        self.retranslateUi(temperaturepreform)
        QtCore.QMetaObject.connectSlotsByName(temperaturepreform)

    def retranslateUi(self, temperaturepreform):
        _translate = QtCore.QCoreApplication.translate
        temperaturepreform.setWindowTitle(_translate("temperaturepreform", "Form"))
        self.temperatureprebackbutton.setText(_translate("temperaturepreform", "BACK"))
        self.temperaturepreforecastbutton.setText(_translate("temperaturepreform", "See Forecast Chart"))
from mmatplotlibwidget import MatplotlibWidget


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    temperaturepreform = QtWidgets.QWidget()
    ui = Ui_temperaturepreform()
    ui.setupUi(temperaturepreform)
    temperaturepreform.show()
    sys.exit(app.exec_())
